version: "2.1"
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"

services:
  greendns:
    container_name: greendns
    image: faicker/greendns:latest
    restart: unless-stopped
    ports:
      - "${DNS_LISTEN:-127.0.0.1:53}:5353/udp"
    environment:
      - LDS=127.0.0.1:5453
      - RDS=127.0.0.1:5454
      - CACHE=true
      - RFC1918=true
      - LISTEN=0.0.0.0:5353
    logging: *default-logging

  pdnsd:
    container_name: pdnsd
    image: faicker/pdnsd:latest
    volumes:
      - ./pdnsd.conf:/etc/pdnsd.conf
    restart: unless-stopped
    network_mode: "service:greendns"
    logging: *default-logging

  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: faicker/dnscrypt-proxy-2:latest
    volumes:
      - ./dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro
    restart: unless-stopped
    network_mode: "service:greendns"
    logging: *default-logging

